import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';
import { gql, useQuery } from 'urql';
import { withUrql } from '../modules/urqlClient';

const POKEMONS_QUERY = gql`
    query {
        pokemons(limit: 5) {
            id
            name
        }
    }
`;

const Home: NextPage = () => {
  const [res] = useQuery({ query: POKEMONS_QUERY });
  let res1body;

  if (res.fetching) {
    res1body = (<div>loading...</div>);
  } else {
    // @ts-ignore
    res1body = res.data.pokemons.map(pokemon => (
          <div key={pokemon.id}>
            {pokemon.id} - {pokemon.name}
          </div>
        ));
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className={styles.main}>
        <div>
          <h1>client</h1>
          {res1body}
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href='https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app'
          target='_blank'
          rel='noopener noreferrer'
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src='/vercel.svg' alt='Vercel Logo' width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
};

export default withUrql(Home);
