import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';
import Button from '@mui/material/Button';


import { gql } from '@apollo/client';
import { client } from '../apollo/client';


const Home: NextPage = ({ countries }) => {
  console.log(countries);
  const lst = countries.map(v => {
    return (
      <div key={v.code} className={styles.grid}>
        <h3>{v.code}({v.emoji})</h3>
        <p>
          {v.name}
        </p>
      </div>);
  });
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className={styles.main}>
        {lst}
      </main>

      <footer className={styles.footer}>
        <a
          href='https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app'
          target='_blank'
          rel='noopener noreferrer'
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src='/vercel.svg' alt='Vercel Logo' width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
};

export async function getStaticProps() {
  const { data } = await client.query({
    query: gql`
        query Countries {
            countries {
                code
                name
                emoji
            }
        }
    `,
  });

  return {
    props: {
      countries: data.countries.slice(0, 4),
    },
  };
}

export default Home;
