import type { InferGetStaticPropsType, NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';

import { CountriesDocument, Country } from '../__generated__/graphql';
import { Card, CardContent, Grid, Typography } from '@mui/material';
import { initializeApollo } from '../modules/WithApollo';

type Props = InferGetStaticPropsType<typeof getStaticProps>;

const Home: NextPage<Props> = ({ countries }) => {
  const lst = countries.map((v) => {
    return (
      <Grid item key={v.code}>

        <Card variant="outlined">
          <CardContent>
            <Typography variant="h5" component="div">
              {v.code}({v.emoji})
            </Typography>
            <Typography variant="body2">{v.name}</Typography>
          </CardContent>
        </Card>
      </Grid>
    );
  });
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className={styles.main}>
        <Grid container spacing={2} justifyContent="center">
          {lst}
        </Grid>
      </main>

      <footer className={styles.footer}>
        <a
          href='https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app'
          target='_blank'
          rel='noopener noreferrer'
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src='/vercel.svg' alt='Vercel Logo' width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
};

export async function getStaticProps() {
  const apolloClient = initializeApollo();
  const { data } = await apolloClient.query({
    query: CountriesDocument,
  });

  const countries: Country[] = data.countries.slice(0, 4);
  return {
    props: {
      countries,
    },
  };
}

export default Home;
